import type { Metadata } from 'next'
import { Barlow_Condensed } from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/header'

const barlow = Barlow_Condensed({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '700']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={barlow.className}>
				<div className="w-full h-screen relative">
					<Header />
					<main className="w-full h-full">{children}</main>
				</div>
			</body>
		</html>
	)
}
